### ISSUE TITLE
Archive all migrations from 2023 and older

### ISSUE THREAD

**Issue by kulla** [serlo/db-migrations#287]

**Comment by hejtful** [comment]
How do we archive migrations? Just move them to the `archive` folder, or is there more to it?

**Comment by AndreasHuber** [comment]
https://github.com/serlo/db-migrations/pull/290/files is a recent example, so it seems to be moving both the .js and .ts to archive.

**Comment by hejtful** [comment]
But not all migrations have their transpiled `.js` files moved. I guess those are the ones that have actually been run. In case a migration was never run, we can move the `.js` file as well. @kulla Could you confirm this please?
