### ISSUE TITLE
Build scripts into migrations automatically

### ISSUE THREAD

**Issue by kulla** [serlo/db-migrations#291]
Sometimes I miss building all scripts before running `yarn push-image` or before deploying a new version. -> Thus via Dockerfile those files should be build automatically (Then we do not need to store `migrations` any more)

**Comment by AndreasHuber** [comment]
We don't we let the CI workflow build the scripts instead?

**Comment by kulla** [comment]
> Why don't we let the CI workflow build the scripts instead?

Good point. It was done previously to have more control which version of the migration shall be run. However a migration with the same name is never run twice. I updated the issue acordingly
