### ISSUE TITLE
Major simplification of `event_*` tables

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/db-migrations#344]
Currently, the database structure regarding `event` is absurdly complex.

For example, to get the the parent of a checkout revision event we have to go through the `event_parameter` table and then to the `event_parameter_uuid`, besides that we have to see in the `event_parameter_string` the corresponding reason.

A much simpler way of dealing with it would be to have nullable columns in the `event_log` table. Or we could have just one table like `event_data` and have all info there. Anyway, we should figure out a simpler solution, of course with the corresponding db migration.

**Comment by kulla** [comment]
The following file contains all current descriptions of events:

https://github.com/serlo/api.serlo.org/blob/af1639f0a6e6e2ebca63083016cfa85ba103dfec/packages/server/src/schema/events/event.ts#L439-L533

There are at most two extra uuid_paramaters and at most one string parameter needed. A first easy simplification is to merge all extra `event_*` tables into one with the parameters:

* `uuid_parameter: Int or null`
* `uuid_paramater2: Int or null`
* `string_parameter: String or null`

**Comment by kulla** [comment]
A next step might be to store JSON in the event table. Also the following renamings can be done:

* Rename `event_log` into `event`
* Rename `event` into `event_type`
