### ISSUE TITLE
Replace the usage of vercel/ncc with esbuild

### ISSUE THREAD

**Issue by eliflores** [serlo/db-migrations#82]
**Context**: This is one of the ideas that came up while working on https://github.com/serlo/db-migrations/issues/66 ✨ 

---
Replace the usage of [ncc](https://github.com/vercel/ncc) [here](https://github.com/serlo/db-migrations/blob/main/scripts/build.ts#L53) with [esbuild](https://esbuild.github.io/) 

👍 From the [esbuild](https://esbuild.github.io/) website it seems that the building process would be faster (let's measure it!)
👍 All the transitive dependencies for  [ncc](https://github.com/vercel/ncc) would not be needed any more, and [esbuild](https://esbuild.github.io/) is bundled with everything it needs (only one more package to install).

**Comment by kulla** [comment]
Fixed by https://github.com/serlo/db-migrations/commit/daabf8ddae754aeb93a0c5430d787567f509a960
